import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { ArchitectureNode, Currency } from '../models/architecture.model';
import * as serviceCostModelData from '../data/service-cost-model.json';
import * as fallbackPricesData from '../data/regions/us-east-1.json';

const fallbackPrices = (fallbackPricesData as any).default || fallbackPricesData;

export interface CostBreakdownLine {
  label: string;
  formula: string;
  value: number;
  note?: string;
}

export interface CostBreakdown {
  lines: CostBreakdownLine[];
  total: number;
  freeTierNote?: string;
}

@Injectable({ providedIn: 'root' })
export class CostService {
  public readonly regions = [
    { code: 'us-east-1', name: 'US East (N. Virginia)' },
    { code: 'us-east-2', name: 'US East (Ohio)' },
    { code: 'us-west-1', name: 'US West (N. California)' },
    { code: 'us-west-2', name: 'US West (Oregon)' },
    { code: 'ca-central-1', name: 'Canada (Central)' },
    { code: 'eu-west-1', name: 'Europe (Ireland)' },
    { code: 'eu-west-2', name: 'Europe (London)' },
    { code: 'eu-west-3', name: 'Europe (Paris)' },
    { code: 'eu-central-1', name: 'Europe (Frankfurt)' },
    { code: 'eu-central-2', name: 'Europe (Zurich)' },
    { code: 'eu-north-1', name: 'Europe (Stockholm)' },
    { code: 'eu-south-1', name: 'Europe (Milan)' },
    { code: 'eu-south-2', name: 'Europe (Spain)' },
    { code: 'ap-east-1', name: 'Asia Pacific (Hong Kong)' },
    { code: 'ap-south-1', name: 'Asia Pacific (Mumbai)' },
    { code: 'ap-south-2', name: 'Asia Pacific (Hyderabad)' },
    { code: 'ap-northeast-1', name: 'Asia Pacific (Tokyo)' },
    { code: 'ap-northeast-2', name: 'Asia Pacific (Seoul)' },
    { code: 'ap-northeast-3', name: 'Asia Pacific (Osaka)' },
    { code: 'ap-southeast-1', name: 'Asia Pacific (Singapore)' },
    { code: 'ap-southeast-2', name: 'Asia Pacific (Sydney)' },
    { code: 'ap-southeast-3', name: 'Asia Pacific (Jakarta)' },
    { code: 'ap-southeast-4', name: 'Asia Pacific (Melbourne)' },
    { code: 'me-south-1', name: 'Middle East (Bahrain)' },
    { code: 'me-central-1', name: 'Middle East (UAE)' },
    { code: 'sa-east-1', name: 'South America (São Paulo)' },
    { code: 'af-south-1', name: 'Africa (Cape Town)' }
  ];


  private loadedPricing: any = fallbackPrices;
  private currentRegionCode: string = 'us-east-1';

  /**
   * Emits the region code when a user selects a region that has no
   * pre-generated pricing file in Cloudflare KV. Emits null when the
   * popup should be dismissed or on a successful load.
   */
  public readonly unsupportedRegion$ = new BehaviorSubject<string | null>(null);

  private readonly conversionRates: Record<Currency, number> = {
    USD: 1.0,
    EUR: 0.92,
    GBP: 0.79,
    INR: 83.0,
    JPY: 150.0
  };

  private readonly currencySymbols: Record<Currency, string> = {
    USD: '$',
    EUR: '€',
    GBP: '£',
    INR: '₹',
    JPY: '¥'
  };

  private readonly costModel = (serviceCostModelData as any).serviceCostModel || (serviceCostModelData as any).default?.serviceCostModel || {};
  private activeNodes: ArchitectureNode[] = [];

  async loadRegionPricing(regionCode: string): Promise<void> {
    this.currentRegionCode = regionCode;
    // Clear any previous unsupported-region state
    this.unsupportedRegion$.next(null);
    console.log(`[CostService] Loading pricing for region: ${regionCode}`);

    try {
      const response = await fetch(`/api/prices?region=${regionCode}`);

      // 404 → region not yet generated by the Worker
      if (response.status === 404) {
        const body = await response.json();
        if (body.unsupportedRegion) {
          console.warn(`[CostService] ⚠️  Region "${regionCode}" is not supported yet (no pricing file in KV).`);
          this.unsupportedRegion$.next(regionCode);
          return; // Do NOT overwrite loadedPricing — keep previous region's data
        }
      }

      if (!response.ok) throw new Error(`HTTP ${response.status}`);

      const xCache = response.headers.get('X-Cache') || 'UNKNOWN';
      this.loadedPricing = await response.json();
      console.log(`[CostService] ✅ Pricing loaded for: ${regionCode} (source: ${xCache})`);

    } catch (e) {
      console.warn(`[CostService] Failed to fetch pricing for ${regionCode}. Keeping previous pricing.`, e);
      // On network error, do not change loadedPricing — caller can decide to revert
    }
  }

  getCurrencySymbol(currency: Currency): string {
    return this.currencySymbols[currency];
  }

  calculateTotalMonthlyCost(nodes: ArchitectureNode[], currency: Currency = 'USD', region: string = 'us-east-1'): number {
    this.activeNodes = nodes;
    const totalUsd = nodes.reduce((sum, node) => sum + this.calculateNodeCostUsd(node, region, nodes), 0);
    return totalUsd * this.conversionRates[currency];
  }

  private getPricingFactorsForRegion(serviceType: string, regionCode: string): any {
    const basePf = fallbackPrices.services[serviceType] || {};
    const baseModel = this.costModel[serviceType] || {};
    if (baseModel.regionOverride) {
      return basePf;
    }

    if (this.loadedPricing && this.loadedPricing.regionCode === regionCode) {
      return this.loadedPricing.services[serviceType] || {};
    }

    // Temporary fallback if requested region isn't loaded yet
    return basePf;
  }

  private getVal(config: any, serviceType: string, key: string, fallback: any): any {
    if (config && config[key] !== undefined && config[key] !== null) {
      return config[key];
    }
    const serviceModel = this.costModel[serviceType];
    if (serviceModel) {
      const primary = serviceModel.primaryParams?.find((p: any) => p.key === key);
      if (primary && primary.default !== undefined) return primary.default;

      const costParam = serviceModel.costParams?.find((p: any) => p.key === key);
      if (costParam && costParam.default !== undefined) return costParam.default;
    }
    return fallback;
  }

  private evaluateServiceCost(
    node: ArchitectureNode,
    pf: any,
    config: any,
    lines: CostBreakdownLine[],
    allNodes?: ArchitectureNode[]
  ): number {
    let total = 0;

    switch (node.type) {
      case 'apiGateway': {
        const type = this.getVal(config, 'apiGateway', 'type', 'rest');
        const throughput = this.getVal(config, 'apiGateway', 'throughput', 2000);
        const reqsM = throughput * 2.628;
        
        let reqCost = 0;
        let formula = '';
        const pricingGroup = pf.requestsM?.[type] || {};

        if (typeof pricingGroup === 'number') {
          // Fallback if the pricing structure is flat/old
          reqCost = reqsM * pricingGroup;
          formula = `${reqsM.toLocaleString(undefined, { maximumFractionDigits: 2 })}M × $${pricingGroup.toFixed(2)}/M`;
        } else {
          const t1 = pricingGroup.tier1 !== undefined ? pricingGroup.tier1 : (type === 'rest' ? 3.50 : 1.00);
          const t2 = pricingGroup.tier2 !== undefined ? pricingGroup.tier2 : (type === 'rest' ? 2.80 : (type === 'http' ? 0.90 : 0.80));

          if (type === 'http') {
            if (reqsM <= 300) {
              reqCost = reqsM * t1;
              formula = `${reqsM.toLocaleString(undefined, { maximumFractionDigits: 2 })}M × $${t1.toFixed(2)}/M`;
            } else {
              reqCost = (300 * t1) + ((reqsM - 300) * t2);
              formula = `(300M × $${t1.toFixed(2)}/M) + (${(reqsM - 300).toLocaleString(undefined, { maximumFractionDigits: 2 })}M × $${t2.toFixed(2)}/M)`;
            }
          } else if (type === 'websocket') {
            if (reqsM <= 1000) {
              reqCost = reqsM * t1;
              formula = `${reqsM.toLocaleString(undefined, { maximumFractionDigits: 2 })}M × $${t1.toFixed(2)}/M`;
            } else {
              reqCost = (1000 * t1) + ((reqsM - 1000) * t2);
              formula = `(1,000M × $${t1.toFixed(2)}/M) + (${(reqsM - 1000).toLocaleString(undefined, { maximumFractionDigits: 2 })}M × $${t2.toFixed(2)}/M)`;
            }
          } else { // 'rest'
            const t3 = pricingGroup.tier3 !== undefined ? pricingGroup.tier3 : 2.38;
            const t4 = pricingGroup.tier4 !== undefined ? pricingGroup.tier4 : 1.51;
            let remaining = reqsM;
            
            const tier1Vol = Math.min(remaining, 333);
            reqCost += tier1Vol * t1;
            remaining -= tier1Vol;

            let formulaParts = [`${tier1Vol.toLocaleString(undefined, { maximumFractionDigits: 2 })}M × $${t1.toFixed(2)}/M`];

            if (remaining > 0) {
              const tier2Vol = Math.min(remaining, 667);
              reqCost += tier2Vol * t2;
              remaining -= tier2Vol;
              formulaParts.push(`${tier2Vol.toLocaleString(undefined, { maximumFractionDigits: 2 })}M × $${t2.toFixed(2)}/M`);
            }
            if (remaining > 0) {
              const tier3Vol = Math.min(remaining, 19000);
              reqCost += tier3Vol * t3;
              remaining -= tier3Vol;
              formulaParts.push(`${tier3Vol.toLocaleString(undefined, { maximumFractionDigits: 2 })}M × $${t3.toFixed(2)}/M`);
            }
            if (remaining > 0) {
              reqCost += remaining * t4;
              formulaParts.push(`${remaining.toLocaleString(undefined, { maximumFractionDigits: 2 })}M × $${t4.toFixed(2)}/M`);
            }
            formula = formulaParts.join(' + ');
          }
        }

        lines.push({ label: type.toUpperCase() + ' API Requests', formula: formula, value: reqCost });
        
        let cacheCost = 0;
        if (type === 'rest' && config.cacheGB && config.cacheGB !== '0') {
          cacheCost = pf.cacheRates?.[config.cacheGB] || 14.40;
          lines.push({ label: 'Dedicated Cache', formula: config.cacheGB + ' GB Tier', value: cacheCost });
        }
        total = reqCost + cacheCost;
        break;
      }

      case 'route53': {
        const zones = this.getVal(config, 'route53', 'hostedZones', 0);
        let zoneCost = 0;
        let zoneFormula = '';
        if (zones <= 25) {
          zoneCost = zones * (pf.zoneMonthly || 0.50);
          zoneFormula = `${zones} Zones × $${(pf.zoneMonthly || 0.50).toFixed(2)}/zone/mo`;
        } else {
          zoneCost = (25 * (pf.zoneMonthly || 0.50)) + ((zones - 25) * 0.10);
          zoneFormula = `(25 Zones × $${(pf.zoneMonthly || 0.50).toFixed(2)}) + (${zones - 25} Zones × $0.10)/mo`;
        }
        lines.push({ label: 'Hosted Zones', formula: zoneFormula, value: zoneCost });

        const capacity = this.getVal(config, 'route53', 'throughput', 80);
        const queriesM = capacity * 2.628;

        const stdRate = pf.standardM || 0.40;
        let queryCost = 0;
        let queryFormula = '';
        if (queriesM <= 1000) {
          queryCost = queriesM * stdRate;
          queryFormula = `${queriesM.toLocaleString(undefined, { maximumFractionDigits: 2 })}M queries × $${stdRate.toFixed(2)}/M`;
        } else {
          queryCost = (1000 * stdRate) + ((queriesM - 1000) * 0.20);
          queryFormula = `(1,000M × $${stdRate.toFixed(2)}) + (${(queriesM - 1000).toLocaleString(undefined, { maximumFractionDigits: 2 })}M × $0.20)/M`;
        }
        lines.push({ label: 'Standard DNS Queries', formula: queryFormula, value: queryCost });

        total = zoneCost + queryCost;
        break;
      }

      case 'cloudfront': {
        const region = this.getVal(config, 'cloudfront', 'region', 'us-eu');
        const dtOut = this.getVal(config, 'cloudfront', 'dataTransferOut', 1000);
        const dtRate = pf.dtOut?.[region] || 0.085;
        const dtCost = dtOut * dtRate;
        lines.push({ label: 'Data Transfer Out', formula: dtOut + ' GB × $' + dtRate + '/GB', value: dtCost });
        const reqsM = this.getVal(config, 'cloudfront', 'requestsM', 10);
        const reqRate = pf.requestsM?.[region] || 1.0;
        const reqCost = reqsM * reqRate;
        lines.push({ label: 'Requests', formula: reqsM + 'M × $' + reqRate + '/M', value: reqCost });
        let wafCost = 0;
        if (config.wafEnabled) {
          wafCost = (pf.wafBase || 5.0) + (reqsM * (pf.wafRequestM || 0.60));
          lines.push({ label: 'WAF Integration', formula: '$' + (pf.wafBase || 5.0).toFixed(2) + ' + (' + reqsM + 'M × $' + (pf.wafRequestM || 0.60).toFixed(2) + '/M)', value: wafCost });
        }
        total = dtCost + reqCost + wafCost;
        break;
      }

      case 'lambda': {
        const isArm = config.architecture === 'arm64';
        const memoryMB = this.getVal(config, 'lambda', 'memoryMB', 512);
        const invocationsM = this.getVal(config, 'lambda', 'invocationsM', 10);
        const durationMs = this.getVal(config, 'lambda', 'durationMs', 200);

        const reqCost = invocationsM * (pf.requestM || 0.20);
        lines.push({ label: 'Requests', formula: `${invocationsM}M × $${(pf.requestM || 0.20).toFixed(2)}/M`, value: reqCost });

        const gbSec = invocationsM * 1000000 * (durationMs / 1000) * (memoryMB / 1024);
        const compRate = isArm ? (pf.gbSec_arm || 0.0000133334) : (pf.gbSec_x86 || 0.0000166667);
        const compCost = gbSec * compRate;
        lines.push({ label: `Compute (${isArm ? 'ARM' : 'x86'})`, formula: `${gbSec.toLocaleString(undefined, { maximumFractionDigits: 0 })} GB-sec × $${compRate.toFixed(6)}/GB-sec`, value: compCost });

        let ephCost = 0;
        const ephMB = this.getVal(config, 'lambda', 'ephemeralMB', 512);
        if (ephMB > 512) {
          const ephGB = (ephMB - 512) / 1024;
          ephCost = invocationsM * 1000000 * (durationMs / 1000) * ephGB * (pf.ephemeralGB_Sec || 0.0000000309);
          lines.push({ label: 'Ephemeral Storage', formula: `${ephGB.toFixed(2)} extra GB × $${(pf.ephemeralGB_Sec || 0.0000000309).toFixed(10)}/GB-sec`, value: ephCost });
        }

        let provCost = 0;
        const provConcurrency = this.getVal(config, 'lambda', 'provConcurrency', 0);
        if (provConcurrency > 0) {
          const provRate = isArm ? (pf.provConcurrency_arm || 0.012) : (pf.provConcurrency_x86 || 0.015);
          provCost = provConcurrency * (memoryMB / 1024) * 730 * provRate;
          lines.push({ label: 'Provisioned Concurrency', formula: `${provConcurrency} Concurrency × ${(memoryMB / 1024).toFixed(2)} GB × 730 hrs × $${provRate.toFixed(3)}`, value: provCost });
        }

        total = reqCost + compCost + ephCost + provCost;
        break;
      }

      case 'ec2': {
        const count = this.getVal(config, 'ec2', 'count', 2);
        const family = this.getVal(config, 'ec2', 'instanceFamily', 't3');
        const size = this.getVal(config, 'ec2', 'instanceSize', 'medium');
        const baseRate = pf.familyRatesLarge?.[family] || 0.096;
        const multiplier = pf.sizeMultipliers?.[size] || 0.5;
        const hourlyRate = baseRate * multiplier;

        const purchase = this.getVal(config, 'ec2', 'purchaseOption', 'on-demand');
        const discount = pf.purchaseDiscounts?.[purchase] || 0;
        const finalRate = hourlyRate * (1 - discount);

        const computeCost = count * finalRate * 730;
        lines.push({ label: `EC2 Compute (${family}.${size})`, formula: `${count} Nodes × $${hourlyRate.toFixed(4)}/hr × 730 hrs × ${((1 - discount) * 100).toFixed(0)}% rate`, value: computeCost });

        const storageType = this.getVal(config, 'ec2', 'storageType', 'gp3');
        const storageSize = this.getVal(config, 'ec2', 'storageSize', 30);
        const storageRate = pf.ebsRates?.[storageType] || 0.08;
        const ebsCost = count * storageSize * storageRate;
        lines.push({ label: `EBS Storage (${storageType})`, formula: `${count} Nodes × ${storageSize} GB × $${storageRate.toFixed(3)}/GB`, value: ebsCost });

        const dto = this.getVal(config, 'ec2', 'dataTransferOut', 100);
        const dtoCost = dto * (pf.dataTransferGB || 0.09);
        if (dtoCost > 0) lines.push({ label: 'Data Transfer Out', formula: `${dto} GB × $${(pf.dataTransferGB || 0.09).toFixed(2)}/GB`, value: dtoCost });

        total = computeCost + ebsCost + dtoCost;
        break;
      }

      case 's3': {
        const sClass = this.getVal(config, 's3', 'storageClass', 'standard');
        const sGB = this.getVal(config, 's3', 'storageGB', 100);
        const sRate = pf.storage?.[sClass] || 0.023;
        const storageCost = sGB * sRate;
        lines.push({ label: 'S3 Storage (' + sClass + ')', formula: sGB + ' GB × $' + sRate + '/GB', value: storageCost });
        const putsM = this.getVal(config, 's3', 'putsM', 1);
        const putRate = pf.puts?.[sClass] || 5.0;
        const putCost = putsM * putRate;
        if (putCost > 0) lines.push({ label: 'PUT Requests', formula: putsM + 'M × $' + putRate + '/M', value: putCost });
        const getsM = this.getVal(config, 's3', 'getsM', 10);
        const getRate = pf.gets?.[sClass] || 0.4;
        const getCost = getsM * getRate;
        if (getCost > 0) lines.push({ label: 'GET Requests', formula: getsM + 'M × $' + getRate + '/M', value: getCost });
        const dtOut = this.getVal(config, 's3', 'dataTransferOut', 100);
        const dtCost = dtOut * (pf.dataTransferGB || 0.09);
        if (dtCost > 0) lines.push({ label: 'Data Transfer Out', formula: dtOut + ' GB × $' + (pf.dataTransferGB || 0.09).toFixed(2) + '/GB', value: dtCost });
        total = storageCost + putCost + getCost + dtCost;
        break;
      }

      case 'elb': {
        const lbType = this.getVal(config, 'elb', 'lbType', 'alb');
        const count = this.getVal(config, 'elb', 'count', 1);
        // RPS from the ELB throughput param — used for LCU calculation
        const rps = this.getVal(config, 'elb', 'throughput', 100);
        // Rule Evaluations (millions/month) — ALB-only
        const rulesM = lbType === 'alb' ? this.getVal(config, 'elb', 'rules', 0) : 0;
        // Customizable connection parameters
        const newConnPct = Number(this.getVal(config, 'elb', 'newConnectionsPercent', 10)) || 10;
        const activeConnsAbs = Number(this.getVal(config, 'elb', 'activeConnections', 1000)) || 1000;

        // Pull package size from connected client node (KB per request)
        const clientNode = allNodes?.find(n => n.type === 'client');
        const packageSizeKB = clientNode ? (clientNode.config?.['packageSize'] || 50) : 50;
        const clientRps = clientNode ? (clientNode.config?.['requestRate'] || rps) : rps;

        // Monthly data volume: rps × 2,628,000 requests/mo × KB ÷ 1,048,576 = GB
        const dataGB = (clientRps * 2_628_000 * packageSizeKB) / 1_048_576;
        const dataStr = dataGB >= 1000
          ? `${(dataGB / 1000).toFixed(2)} TB`
          : `${dataGB.toFixed(1)} GB`;

        const typesPricing = pf.types || {
          alb: { hourly: 0.0225, lcuHour: 0.008 },
          nlb: { hourly: 0.0225, lcuHour: 0.006 },
          clb: { hourly: 0.0250, dataGB: 0.008 },
          gwlb: { hourly: 0.0125, lcuHour: 0.004 }
        };
        const selectedPricing = typesPricing[lbType] || typesPricing.alb || { hourly: 0.0225, lcuHour: 0.008 };

        const hourlyRate = selectedPricing.hourly !== undefined ? selectedPricing.hourly : 0.0225;
        const hrCost = count * 730 * hourlyRate;
        lines.push({
          label: `${lbType.toUpperCase()} Hourly Base`,
          formula: `${count} LB × 730 hrs × $${hourlyRate.toFixed(4)}/hr`,
          value: hrCost
        });

        if (lbType === 'clb') {
          // CLB charges per GB processed (no LCU model)
          const dataRate = selectedPricing.dataGB !== undefined ? selectedPricing.dataGB : 0.008;
          const dataCost = dataGB * dataRate;
          lines.push({
            label: 'CLB Data Processing',
            formula: `${dataStr} × $${dataRate.toFixed(4)}/GB`,
            value: dataCost
          });
          total = hrCost + dataCost;
        } else {
          // New connections per second = RPS × newConnPct%
          const newConnPerSec = rps * (newConnPct / 100);

          // Real AWS LCU formula: LCU = max(newConnDim, activeConnDim, dataProcessedDim, ruleEvalDim)
          // Dimensions (per LCU definition):
          //   New connections  : 25 new connections per second per LCU
          //   Active connections: 3,000 active connections per LCU
          //   Data processed   : 1 GB per hour per LCU → dataGB / 730 hrs
          //   Rule evaluations : 1,000 rule evaluations per second per LCU (ALB only, first 10 rules free)
          const newConnDim    = newConnPerSec / 25;
          const activeConnDim = activeConnsAbs / 3000;                        // absolute concurrent connections ÷ 3,000
          const dataDim       = dataGB / 730;                                 // GB/month ÷ 730 hrs = GB/hr
          const ruleDim       = lbType === 'alb' ? (rulesM * 1_000_000 / 3600) / 1000 : 0; // rule-evals/sec ÷ 1000

          const lcus = Math.max(newConnDim, activeConnDim, dataDim, ruleDim);
          const lcuRate = selectedPricing.lcuHour !== undefined ? selectedPricing.lcuHour : 0.008;
          const lcuCost = count * lcus * 730 * lcuRate;

          lines.push({
            label: `${lbType.toUpperCase()} LCU Cost`,
            formula: `max(newConn: ${newConnDim.toFixed(2)}, activeConn: ${activeConnDim.toFixed(2)}, data: ${dataDim.toFixed(2)}, rules: ${ruleDim.toFixed(2)}) = ${lcus.toFixed(2)} LCUs × 730 hrs × $${lcuRate.toFixed(4)}/LCU-hr`,
            value: lcuCost,
            note: `Highest dimension billed (${newConnPerSec.toFixed(1)} new conn/s, ${activeConnsAbs.toLocaleString()} active conns, ${dataStr}/mo processed)`
          });
          total = hrCost + lcuCost;
        }
        break;
      }

      case 'vpc': {
        const ep = this.getVal(config, 'vpc', 'endpoints', 0);
        const epCost = ep * 730 * (pf.endpointHourly || 0.01);
        if (epCost > 0) lines.push({ label: 'VPC Endpoints (Hourly)', formula: ep + ' endpoints × 730 hrs × $' + (pf.endpointHourly || 0.01).toFixed(2) + '/hr', value: epCost });
        const epGB = this.getVal(config, 'vpc', 'endpointGB', 0);
        const gbCost = epGB * (pf.endpointGB || 0.01);
        if (gbCost > 0) lines.push({ label: 'VPC Endpoint Data', formula: epGB + ' GB × $' + (pf.endpointGB || 0.01).toFixed(2) + '/GB', value: gbCost });
        total = epCost + gbCost;
        break;
      }

      case 'natGateway': {
        const count = this.getVal(config, 'natGateway', 'count', 1);
        const hrCost = count * 730 * (pf.hourly || 0.045);
        lines.push({ label: 'NAT Gateway Hourly', formula: count + ' NATs × 730 hrs × $' + (pf.hourly || 0.045).toFixed(3) + '/hr', value: hrCost });
        const dataGB = this.getVal(config, 'natGateway', 'dataGB', 100);
        const dataCost = dataGB * (pf.dataGB || 0.045);
        lines.push({ label: 'Data Processed', formula: dataGB + ' GB × $' + (pf.dataGB || 0.045).toFixed(3) + '/GB', value: dataCost });
        total = hrCost + dataCost;
        break;
      }

      case 'cloudWatch': {
        const met = this.getVal(config, 'cloudWatch', 'metrics', 100);
        const costMet = met * (pf.metricRate || 0.30);
        lines.push({ label: 'Metrics', formula: met + ' Metrics × $' + (pf.metricRate || 0.30).toFixed(2), value: costMet });
        const gb = this.getVal(config, 'cloudWatch', 'logsGB', 50);
        const costGb = gb * (pf.logsGB || 0.50);
        lines.push({ label: 'Log Ingestion', formula: gb + ' GB × $' + (pf.logsGB || 0.50).toFixed(2), value: costGb });
        total = costMet + costGb;
        break;
      }

      case 'dynamoDb': {
        const mode = this.getVal(config, 'dynamoDb', 'capacityMode', 'on-demand');
        const sClass = this.getVal(config, 'dynamoDb', 'storageClass', 'standard');
        const rates = pf[sClass === 'infrequent-access' ? 'ia' : 'std'] || pf.std;

        let computeCost = 0;
        if (mode === 'on-demand') {
          const readsM = this.getVal(config, 'dynamoDb', 'readsM', 10);
          const writesM = this.getVal(config, 'dynamoDb', 'writesM', 5);
          const readCost = readsM * rates.readM;
          lines.push({ label: 'Read Requests', formula: `${readsM}M × $${rates.readM}/M`, value: readCost });
          const writeCost = writesM * rates.writeM;
          lines.push({ label: 'Write Requests', formula: `${writesM}M × $${rates.writeM}/M`, value: writeCost });
          computeCost = readCost + writeCost;
        } else {
          const wcu = this.getVal(config, 'dynamoDb', 'wcu', 100);
          const rcu = this.getVal(config, 'dynamoDb', 'rcu', 100);
          const wCost = wcu * rates.wcuHr * 730;
          lines.push({ label: 'Provisioned WCU', formula: `${wcu} WCU × $${rates.wcuHr.toFixed(5)}/hr × 730 hrs`, value: wCost });
          const rCost = rcu * rates.rcuHr * 730;
          lines.push({ label: 'Provisioned RCU', formula: `${rcu} RCU × $${rates.rcuHr.toFixed(5)}/hr × 730 hrs`, value: rCost });
          computeCost = wCost + rCost;
        }

        const storageGB = this.getVal(config, 'dynamoDb', 'storageGB', 50);
        const storageCost = storageGB * rates.storageGB;
        lines.push({ label: `Storage (${sClass})`, formula: `${storageGB} GB × $${rates.storageGB}/GB`, value: storageCost });

        total = computeCost + storageCost;

        if (config.globalTables) {
          const gMult = pf.globalMultiplier || 1.5;
          lines.push({ label: 'Global Tables Replication', formula: `Total × ${(gMult - 1) * 100}% premium`, value: total * (gMult - 1) });
          total = total * gMult;
        }
        break;
      }

      case 'rds': {
        const engine = this.getVal(config, 'rds', 'engine', 'postgresql');
        const instance = this.getVal(config, 'rds', 'instanceClass', 'db.m5.large');
        const count = this.getVal(config, 'rds', 'count', 2);

        const baseRate = pf.instances?.[instance] || 0.171;
        const engineMult = pf.engines?.[engine] || 1.0;
        const multiAzMult = config.multiAz ? (pf.multiAzMultiplier || 2.0) : 1.0;

        const computeCost = count * baseRate * engineMult * multiAzMult * 730;
        lines.push({ label: `RDS Compute (${instance})`, formula: `${count} Nodes × $${baseRate.toFixed(3)}/hr × ${engineMult} engine × ${multiAzMult} AZ × 730 hrs`, value: computeCost });

        const sType = this.getVal(config, 'rds', 'storageType', 'gp3');
        const sGB = this.getVal(config, 'rds', 'storageSize', 100);
        const sRate = pf.storage?.[sType] || 0.115;
        const storageCost = sGB * sRate;
        lines.push({ label: `Storage (${sType})`, formula: `${sGB} GB × $${sRate}/GB`, value: storageCost });

        const backupGB = this.getVal(config, 'rds', 'backupStorage', 100);
        const bRate = pf.backupGB || 0.095;
        const backupCost = backupGB > sGB ? (backupGB - sGB) * bRate : 0;
        if (backupCost > 0) {
          lines.push({ label: 'Backup Storage', formula: `${backupGB - sGB} billed GB × $${bRate}/GB`, value: backupCost });
        }

        total = computeCost + storageCost + backupCost;
        break;
      }

      case 'elastiCache': {
        const count = this.getVal(config, 'elastiCache', 'count', 2);
        const nodeType = this.getVal(config, 'elastiCache', 'nodeType', 'cache.t3.medium');
        const rate = pf.instances?.[nodeType] || 0.068;

        let computeCost = count * rate * 730;
        let formulaStr = `${count} Nodes × $${rate}/hr × 730 hrs`;

        if (config.dataTiering) {
          const mult = pf.tieringPremium || 1.15;
          computeCost *= mult;
          formulaStr += ` × ${mult} tiering`;
        }

        lines.push({ label: `ElastiCache Compute (${nodeType})`, formula: formulaStr, value: computeCost });
        total = computeCost;
        break;
      }

      case 'ecs':
      case 'batch': {
        const isFargate = node.type === 'batch' || (config.launchType !== 'ec2');
        const hrs = node.type === 'batch' ? this.getVal(config, 'batch', 'hoursPerMonth', 100) : this.getVal(config, 'ecs', 'runtimeHours', 730);
        const util = this.getVal(config, node.type, 'utilization', 100) / 100;

        let computeCost = 0;
        if (isFargate) {
          const tasks = this.getVal(config, node.type, 'tasks', node.type === 'ecs' ? 2 : 1);
          const vcpu = Number(this.getVal(config, node.type, 'vCPU', node.type === 'ecs' ? 0.5 : 2));
          const mem = this.getVal(config, node.type, 'memoryGB', node.type === 'ecs' ? 1 : 4);
          const lbl = node.type === 'batch' ? 'jobs' : 'tasks';

          const isArm = config.architecture === 'arm';
          const cpuRate = isArm ? (pf.armCpuHour || 0.03238) : (pf.cpuHour || 0.04048);
          const memRate = isArm ? (pf.armMemHour || 0.00356) : (pf.memHour || 0.004445);

          let baseCpuCost = tasks * vcpu * hrs * cpuRate * util;
          let baseMemCost = tasks * mem * hrs * memRate * util;

          const spotUsage = (config.spotUsage || 0) / 100;
          const spotDiscount = pf.spotDiscount || 0.70;
          const blendedMultiplier = (1 - spotUsage) + (spotUsage * (1 - spotDiscount));

          const cpuCost = baseCpuCost * blendedMultiplier;
          lines.push({ label: 'Fargate vCPU Cost', formula: `${tasks} ${lbl} × ${vcpu} vCPU × ${hrs} hrs × $${cpuRate.toFixed(5)}/hr × ${(util * 100).toFixed(0)}% util × ${(blendedMultiplier * 100).toFixed(0)}% blended rate`, value: cpuCost });
          const memCost = baseMemCost * blendedMultiplier;
          lines.push({ label: 'Fargate Memory Cost', formula: `${tasks} ${lbl} × ${mem} GB × ${hrs} hrs × $${memRate.toFixed(5)}/hr × ${(util * 100).toFixed(0)}% util × ${(blendedMultiplier * 100).toFixed(0)}% blended rate`, value: memCost });

          let ephCost = 0;
          const ephGB = this.getVal(config, node.type, 'ephemeralStorage', 20);
          if (ephGB > 20) {
            ephCost = tasks * (ephGB - 20) * hrs * (pf.ephemeralGBHour || 0.000111) * util;
            lines.push({ label: 'Ephemeral Storage', formula: `${tasks} ${lbl} × ${ephGB - 20} extra GB × ${hrs} hrs × $${(pf.ephemeralGBHour || 0.000111).toFixed(6)}/hr`, value: ephCost });
          }

          computeCost = cpuCost + memCost + ephCost;
        } else {
          const nodeCount = this.getVal(config, node.type, 'nodeCount', 2);
          const nodeType = this.getVal(config, node.type, 'nodeInstanceType', 't3.medium');
          const hourlyRate = pf.instances?.[nodeType] || 0.0416;

          const purchase = this.getVal(config, node.type, 'purchaseOption', 'on-demand');
          const discountMap: Record<string, number> = { 'on-demand': 0, 'spot': 0.70, 'reserved': 0.40 };
          const discount = discountMap[purchase] || 0;

          const ec2Cost = nodeCount * hourlyRate * hrs * util * (1 - discount);
          lines.push({ label: `EC2 Nodes (${nodeType})`, formula: `${nodeCount} Nodes × $${hourlyRate.toFixed(4)}/hr × ${hrs} hrs × ${(util * 100).toFixed(0)}% util × ${((1 - discount) * 100).toFixed(0)}% rate`, value: ec2Cost });

          const ebsGB = this.getVal(config, node.type, 'ebsStorage', 30);
          const ebsCost = nodeCount * ebsGB * (pf.ebsGBMonth || 0.08);
          lines.push({ label: 'EBS Storage', formula: `${nodeCount} Nodes × ${ebsGB} GB × $${(pf.ebsGBMonth || 0.08).toFixed(2)}/GB`, value: ebsCost });

          computeCost = ec2Cost + ebsCost;
        }

        const dtGB = this.getVal(config, node.type, 'dataTransferOut', 100);
        const dtCost = dtGB * (pf.dataTransferGB || 0.09);
        lines.push({ label: 'Data Transfer Out', formula: `${dtGB} GB × $${(pf.dataTransferGB || 0.09).toFixed(2)}/GB`, value: dtCost });

        const crossAzGB = this.getVal(config, node.type, 'crossAzTraffic', 50);
        const crossAzCost = crossAzGB * (pf.crossAzGB || 0.01);
        lines.push({ label: 'Cross-AZ Traffic', formula: `${crossAzGB} GB × $${(pf.crossAzGB || 0.01).toFixed(2)}/GB`, value: crossAzCost });

        let elbCost = 0;
        if (config.loadBalancer !== false) {
          elbCost = hrs * (pf.elbHourly || 0.0225);
          lines.push({ label: 'ELB Hourly Base', formula: `${hrs} hrs × $${(pf.elbHourly || 0.0225).toFixed(4)}/hr`, value: elbCost });
        }

        const logsGB = this.getVal(config, node.type, 'cloudWatchLogs', 10);
        const logsCost = logsGB * (pf.logsGB || 0.50);
        lines.push({ label: 'CloudWatch Logs', formula: `${logsGB} GB × $${(pf.logsGB || 0.50).toFixed(2)}/GB`, value: logsCost });

        total = computeCost + dtCost + crossAzCost + elbCost + logsCost;
        break;
      }

      case 'sqs': {
        const reqM = this.getVal(config, 'sqs', 'requestsM', 10);
        const type = this.getVal(config, 'sqs', 'type', 'standard');
        const rate = pf[type] || 0.40;
        const cost = reqM * rate;
        lines.push({ label: 'SQS Requests', formula: reqM + 'M × $' + rate.toFixed(2) + '/M', value: cost });
        total = cost;
        break;
      }

      case 'sns': {
        const pubM = this.getVal(config, 'sns', 'publishM', 10);
        const costPub = pubM * (pf.publish || 0.50);
        lines.push({ label: 'Publish', formula: pubM + 'M × $' + (pf.publish || 0.50).toFixed(2) + '/M', value: costPub });
        const delM = this.getVal(config, 'sns', 'httpM', 10);
        const costDel = delM * (pf.http || 0.60);
        lines.push({ label: 'HTTP Delivery', formula: delM + 'M × $' + (pf.http || 0.60).toFixed(2) + '/M', value: costDel });
        total = costPub + costDel;
        break;
      }

      case 'stepFunctions': {
        const type = this.getVal(config, 'stepFunctions', 'type', 'standard');
        let cost = 0;
        if (type === 'standard') {
          const trans = this.getVal(config, 'stepFunctions', 'transitionsM', 1);
          cost = trans * (pf.standardM || 25.0);
          lines.push({ label: 'Standard Transitions', formula: trans + 'M × $' + (pf.standardM || 25.00).toFixed(2) + '/M', value: cost });
        } else {
          const reqM = this.getVal(config, 'stepFunctions', 'expressReqsM', 10);
          const gbM = this.getVal(config, 'stepFunctions', 'expressGBsecM', 1);
          cost = (reqM * (pf.expressReq || 1.0)) + (gbM * (pf.expressGBsec || 16.67));
          lines.push({ label: 'Express Workflows', formula: reqM + 'M reqs @ $' + (pf.expressReq || 1.0).toFixed(2) + '/M + ' + gbM + 'M GB-s @ $' + (pf.expressGBsec || 16.67).toFixed(2) + '/M', value: cost });
        }
        total = cost;
        break;
      }

      case 'aurora': {
        const mode = this.getVal(config, 'aurora', 'mode', 'serverless-v2');
        const count = this.getVal(config, 'aurora', 'count', 2);

        let computeCost = 0;
        if (mode === 'serverless-v2') {
          const acus = this.getVal(config, 'aurora', 'avgAcus', 2);
          const rate = pf.serverlessAcuHour || 0.12;
          computeCost = count * acus * rate * 730;
          lines.push({ label: 'Aurora Serverless', formula: `${count} Instances × ${acus} ACUs × $${rate}/hr × 730 hrs`, value: computeCost });
        } else {
          const inst = this.getVal(config, 'aurora', 'instanceClass', 'db.r6g.large');
          const rate = pf.instances?.[inst] || 0.26;
          computeCost = count * rate * 730;
          lines.push({ label: `Aurora Provisioned (${inst})`, formula: `${count} Instances × $${rate}/hr × 730 hrs`, value: computeCost });
        }

        const sGB = this.getVal(config, 'aurora', 'storageSize', 100);
        const sRate = pf.storageGB || 0.10;
        const storageCost = sGB * sRate;
        lines.push({ label: 'Storage', formula: `${sGB} GB × $${sRate}/GB`, value: storageCost });

        const ioM = this.getVal(config, 'aurora', 'ioRequestsM', 10);
        const ioRate = pf.ioRequestPerM || 0.20;
        const ioCost = ioM * ioRate;
        if (ioCost > 0) lines.push({ label: 'I/O Requests', formula: `${ioM}M × $${ioRate}/M`, value: ioCost });

        total = computeCost + storageCost + ioCost;
        break;
      }

      case 'eventBridge': {
        const evM = this.getVal(config, 'eventBridge', 'eventsM', 10);
        const cost = evM * (pf.eventM || 1.00);
        lines.push({ label: 'Events Published', formula: evM + 'M × $' + (pf.eventM || 1.00).toFixed(2) + '/M', value: cost });
        total = cost;
        break;
      }

      case 'kinesis': {
        const shards = this.getVal(config, 'kinesis', 'shards', 2);
        const hrRate = pf.shardHour || 0.015;
        const shardCost = shards * 730 * hrRate;
        lines.push({ label: 'Shard Hours', formula: shards + ' Shards × 730 hrs × $' + hrRate + '/hr', value: shardCost });
        const putsM = this.getVal(config, 'kinesis', 'putUnitsM', 10);
        const putRate = pf.putM || 0.014;
        const putCost = putsM * putRate;
        lines.push({ label: 'PUT Payload Units', formula: putsM + 'M × $' + putRate + '/M', value: putCost });
        total = shardCost + putCost;
        break;
      }

      case 'msk': {
        const brokers = this.getVal(config, 'msk', 'brokers', 2);
        const inst = this.getVal(config, 'msk', 'instance', 'kafka.m5.large');
        const rate = pf.instances?.[inst] || 0.24;
        const compCost = brokers * rate * 730;
        lines.push({ label: 'Brokers (' + inst + ')', formula: brokers + ' Brokers × $' + rate + '/hr × 730 hrs', value: compCost });
        const sGB = this.getVal(config, 'msk', 'storageGB', 100);
        const sRate = pf.storageGB || 0.10;
        const storageCost = brokers * sGB * sRate;
        lines.push({ label: 'Broker Storage', formula: brokers + ' Brokers × ' + sGB + ' GB × $' + sRate + '/GB', value: storageCost });
        total = compCost + storageCost;
        break;
      }

      case 'cognito': {
        const mau = this.getVal(config, 'cognito', 'mau', 50000);
        const billable = Math.max(0, mau - (pf.freeTier || 50000));
        const cost = billable * (pf.ratePerUser || 0.0055);
        lines.push({ label: 'MAUs', formula: billable + ' Billable MAUs × $' + (pf.ratePerUser || 0.0055).toFixed(4), value: cost });
        total = cost;
        break;
      }

      case 'waf': {
        const acls = this.getVal(config, 'waf', 'acls', 1);
        const costAcl = acls * (pf.aclMonth || 5.0);
        const rules = this.getVal(config, 'waf', 'rules', 5);
        const costRules = acls * rules * (pf.ruleMonth || 1.0);
        const reqs = this.getVal(config, 'waf', 'requestsM', 10);
        const costReqs = reqs * (pf.reqM || 0.60);
        lines.push({ label: 'WAF ACLs & Rules', formula: acls + ' ACLs, ' + rules + ' Rules', value: costAcl + costRules });
        lines.push({ label: 'Requests Analyzed', formula: reqs + 'M × $' + (pf.reqM || 0.60).toFixed(2) + '/M', value: costReqs });
        total = costAcl + costRules + costReqs;
        break;
      }

      case 'efs': {
        const sClass = this.getVal(config, 'efs', 'storageClass', 'standard');
        const sGB = this.getVal(config, 'efs', 'storageGB', 100);
        const sRate = pf.storage?.[sClass] || 0.30;
        const storageCost = sGB * sRate;
        lines.push({ label: 'EFS Storage (' + sClass + ')', formula: sGB + ' GB × $' + sRate + '/GB', value: storageCost });
        const tp = this.getVal(config, 'efs', 'provisionedThroughput', 0);
        const tpCost = tp * (pf.throughputMBps || 6.0);
        if (tpCost > 0) lines.push({ label: 'Provisioned Throughput', formula: tp + ' MB/s × $' + (pf.throughputMBps || 6.00).toFixed(2) + '/MBps', value: tpCost });
        total = storageCost + tpCost;
        break;
      }

      case 'athena': {
        const dataTB = this.getVal(config, 'athena', 'dataTB', 10);
        const rate = pf.perTB || 5.00;
        const cost = dataTB * rate;
        lines.push({ label: 'Data Scanned', formula: dataTB + ' TB × $' + rate.toFixed(2) + '/TB', value: cost });
        total = cost;
        break;
      }

      case 'secretsManager': {
        const sec = this.getVal(config, 'secretsManager', 'secrets', 10);
        const costSec = sec * (pf.secretMonth || 0.40);
        lines.push({ label: 'Secrets Stored', formula: sec + ' Secrets × $' + (pf.secretMonth || 0.40).toFixed(2), value: costSec });
        const calls = this.getVal(config, 'secretsManager', 'callsM', 1);
        const costCall = calls * (pf.callM || 0.05);
        lines.push({ label: 'API Calls', formula: calls + 'M × $' + (pf.callM || 0.05).toFixed(2) + '/M', value: costCall });
        total = costSec + costCall;
        break;
      }

      case 'transitGateway': {
        const att = this.getVal(config, 'transitGateway', 'attachments', 2);
        const attCost = att * 730 * (pf.attachmentHourly || 0.05);
        lines.push({ label: 'Attachments Hourly', formula: att + ' attachments × 730 hrs × $' + (pf.attachmentHourly || 0.05).toFixed(2) + '/hr', value: attCost });
        const dataGB = this.getVal(config, 'transitGateway', 'dataGB', 100);
        const dataCost = dataGB * (pf.dataGB || 0.02);
        lines.push({ label: 'Data Processed', formula: dataGB + ' GB × $' + (pf.dataGB || 0.02).toFixed(2) + '/GB', value: dataCost });
        total = attCost + dataCost;
        break;
      }

      case 'directConnect': {
        const speed = this.getVal(config, 'directConnect', 'speed', '1g');
        const portRate = pf.portRates?.[speed] || 0.30;
        const portCost = portRate * 730;
        lines.push({ label: 'Port Hourly (' + speed + ')', formula: '730 hrs × $' + portRate + '/hr', value: portCost });
        const dtOut = this.getVal(config, 'directConnect', 'dataTransferOut', 1000);
        const dtCost = dtOut * (pf.dataTransferGB || 0.02);
        lines.push({ label: 'Data Transfer Out', formula: dtOut + ' GB × $' + (pf.dataTransferGB || 0.02).toFixed(2) + '/GB', value: dtCost });
        total = portCost + dtCost;
        break;
      }

      case 'globalAccelerator': {
        const accs = this.getVal(config, 'globalAccelerator', 'accelerators', 1);
        const hrCost = accs * 730 * (pf.hourly || 0.025);
        lines.push({ label: 'Accelerator Hourly', formula: accs + ' Accelerators × 730 hrs × $' + (pf.hourly || 0.025).toFixed(3) + '/hr', value: hrCost });
        const dataGB = this.getVal(config, 'globalAccelerator', 'dataGB', 1000);
        const dtCost = dataGB * (pf.dataGB || 0.015);
        lines.push({ label: 'Data Transfer', formula: dataGB + ' GB × $' + (pf.dataGB || 0.015).toFixed(3) + '/GB', value: dtCost });
        total = hrCost + dtCost;
        break;
      }

      case 'xray': {
        const tr = this.getVal(config, 'xray', 'tracesM', 1);
        const costTr = tr * (pf.recordM || 5.0);
        lines.push({ label: 'Traces Recorded', formula: tr + 'M × $' + (pf.recordM || 5.00).toFixed(2) + '/M', value: costTr });
        const sc = this.getVal(config, 'xray', 'scansM', 10);
        const costSc = sc * (pf.scanM || 0.50);
        lines.push({ label: 'Traces Scanned', formula: sc + 'M × $' + (pf.scanM || 0.50).toFixed(2) + '/M', value: costSc });
        total = costTr + costSc;
        break;
      }

      case 'openSearch': {
        const nodes = this.getVal(config, 'openSearch', 'nodes', 2);
        const inst = this.getVal(config, 'openSearch', 'instance', 'r6g.large');
        const rate = pf.instances?.[inst] || 0.167;
        const compCost = nodes * rate * 730;
        lines.push({ label: 'Data Nodes (' + inst + ')', formula: nodes + ' Nodes × $' + rate + '/hr × 730 hrs', value: compCost });
        const gb = this.getVal(config, 'openSearch', 'storageGB', 100);
        const sRate = pf.storageGB || 0.122;
        const storageCost = gb * sRate;
        lines.push({ label: 'EBS Storage', formula: gb + ' GB × $' + sRate + '/GB', value: storageCost });
        total = compCost + storageCost;
        break;
      }

      case 'redshift': {
        const type = this.getVal(config, 'redshift', 'type', 'provisioned');
        const hours = this.getVal(config, 'redshift', 'hours', 730);
        let compCost = 0;
        if (type === 'provisioned') {
          const nodes = this.getVal(config, 'redshift', 'nodes', 2);
          const inst = this.getVal(config, 'redshift', 'instance', 'ra3.xlplus');
          const rate = pf.instances?.[inst] || 1.086;
          compCost = nodes * rate * hours;
          lines.push({ label: 'Provisioned Nodes (' + inst + ')', formula: nodes + ' Nodes × $' + rate + '/hr × ' + hours + ' hrs', value: compCost });
        } else {
          const rpus = this.getVal(config, 'redshift', 'rpus', 32);
          const rate = pf.rpuHour || 0.36;
          compCost = rpus * rate * hours;
          lines.push({ label: 'Serverless Compute', formula: rpus + ' RPUs × $' + rate + '/hr × ' + hours + ' hrs', value: compCost });
        }
        const tb = this.getVal(config, 'redshift', 'storageTB', 1);
        const sRate = pf.storageTB || 24.576;
        const storageCost = tb * sRate;
        lines.push({ label: 'Managed Storage', formula: tb + ' TB × $' + sRate.toFixed(3) + '/TB', value: storageCost });
        total = compCost + storageCost;
        break;
      }

      case 'glue': {
        const dpus = this.getVal(config, 'glue', 'dpus', 10);
        const hours = this.getVal(config, 'glue', 'hours', 50);
        const rate = pf.dpuHour || 0.44;
        const jobCost = dpus * hours * rate;
        if (jobCost > 0) lines.push({ label: 'ETL Jobs', formula: dpus + ' DPUs × ' + hours + ' hrs × $' + rate + '/hr', value: jobCost });
        const crawlHr = this.getVal(config, 'glue', 'crawlers', 10);
        const crawlCost = crawlHr * rate;
        if (crawlCost > 0) lines.push({ label: 'Crawlers', formula: crawlHr + ' DPU-hrs × $' + rate + '/hr', value: crawlCost });
        total = jobCost + crawlCost;
        break;
      }

      case 'emr': {
        const nodes = this.getVal(config, 'emr', 'nodes', 3);
        const inst = this.getVal(config, 'emr', 'instance', 'm5.xlarge');
        const hours = this.getVal(config, 'emr', 'hours', 100);
        const rate = pf.instances?.[inst] || 0.24;
        const cost = nodes * rate * hours;
        lines.push({ label: 'EMR Cluster (' + inst + ')', formula: nodes + ' Nodes × $' + rate + '/hr × ' + hours + ' hrs', value: cost });
        total = cost;
        break;
      }

      case 'kinesisFirehose': {
        const gb = this.getVal(config, 'kinesisFirehose', 'dataGB', 100);
        const rate = pf.ingestGB || 0.029;
        const ingestCost = gb * rate;
        lines.push({ label: 'Data Ingestion', formula: gb + ' GB × $' + rate + '/GB', value: ingestCost });
        let convCost = 0;
        if (config.conversion) {
          const cRate = pf.convertGB || 0.018;
          convCost = gb * cRate;
          lines.push({ label: 'Format Conversion', formula: gb + ' GB × $' + cRate + '/GB', value: convCost });
        }
        total = ingestCost + convCost;
        break;
      }

      case 'mq': {
        const b = this.getVal(config, 'mq', 'brokers', 1);
        const inst = this.getVal(config, 'mq', 'instance', 'mq.m5.large');
        const rate = pf.instances?.[inst] || 0.34;
        const cost = b * rate * 730;
        lines.push({ label: 'MQ Brokers', formula: b + ' Brokers × $' + rate + '/hr × 730 hrs', value: cost });
        total = cost;
        break;
      }

      case 'kms': {
        const keys = this.getVal(config, 'kms', 'keys', 5);
        const costKeys = keys * (pf.keyMonth || 1.0);
        lines.push({ label: 'CMKs', formula: keys + ' Keys × $' + (pf.keyMonth || 1.00).toFixed(2), value: costKeys });
        const reqM = this.getVal(config, 'kms', 'requestsM', 10);
        const costReq = reqM * (pf.reqM || 0.03);
        lines.push({ label: 'API Requests', formula: reqM + 'M × $' + (pf.reqM || 0.03).toFixed(2) + '/M', value: costReq });
        total = costKeys + costReq;
        break;
      }

      case 'shield': {
        const adv = this.getVal(config, 'shield', 'advanced', false);
        const cost = adv ? (pf.advancedMonth || 3000) : 0;
        if (adv) {
          lines.push({ label: 'Shield Advanced', formula: '$' + (pf.advancedMonth || 3000) + ' / month flat', value: cost });
        }
        total = cost;
        break;
      }

      case 'organizations': {
        lines.push({ label: 'AWS Organizations is free', formula: '0.00', value: 0 });
        total = 0;
        break;
      }

      case 'codePipeline': {
        const p = this.getVal(config, 'codePipeline', 'pipelines', 5);
        const cost = p * (pf.pipelineMonth || 1.0);
        lines.push({ label: 'Active Pipelines', formula: p + ' Pipelines × $' + (pf.pipelineMonth || 1.00).toFixed(2), value: cost });
        total = cost;
        break;
      }

      case 'codeBuild': {
        const min = this.getVal(config, 'codeBuild', 'minutes', 1000);
        const type = this.getVal(config, 'codeBuild', 'computeType', 'general1.small');
        const rate = pf.rates?.[type] || 0.005;
        const cost = min * rate;
        lines.push({ label: 'Build Compute', formula: min + ' min × $' + rate + '/min', value: cost });
        total = cost;
        break;
      }

      case 'codeDeploy': {
        const up = this.getVal(config, 'codeDeploy', 'onPremUpdates', 0);
        const cost = up * (pf.updateRate || 0.02);
        if (cost > 0) {
          lines.push({ label: 'On-Prem Updates', formula: up + ' Updates × $' + (pf.updateRate || 0.02).toFixed(2), value: cost });
        }
        total = cost;
        break;
      }

      case 'bedrock': {
        const m = this.getVal(config, 'bedrock', 'model', 'claude-haiku');
        const inM = this.getVal(config, 'bedrock', 'inTokensM', 10);
        const outM = this.getVal(config, 'bedrock', 'outTokensM', 2);
        const inRate = pf.inM?.[m] || 0.25;
        const outRate = pf.outM?.[m] || 1.25;
        const inCost = inM * inRate;
        const outCost = outM * outRate;
        lines.push({ label: 'Input Tokens (' + m + ')', formula: inM + 'M × $' + inRate + '/M', value: inCost });
        lines.push({ label: 'Output Tokens (' + m + ')', formula: outM + 'M × $' + outRate + '/M', value: outCost });
        total = inCost + outCost;
        break;
      }

      case 'sageMaker': {
        const type = this.getVal(config, 'sageMaker', 'type', 'instance');
        let computeCost = 0;
        if (type === 'instance') {
          const inst = this.getVal(config, 'sageMaker', 'instance', 'ml.m5.large');
          const count = this.getVal(config, 'sageMaker', 'count', 1);
          const rate = pf.instances?.[inst] || 0.134;
          computeCost = count * rate * 730;
          lines.push({ label: 'Hosting (' + inst + ')', formula: count + ' Instances × $' + rate + '/hr × 730 hrs', value: computeCost });
        } else {
          const mem = this.getVal(config, 'sageMaker', 'memoryMB', 2048);
          const dur = this.getVal(config, 'sageMaker', 'durationMs', 500);
          const invM = this.getVal(config, 'sageMaker', 'invocationsM', 1);
          const gbSec = invM * 1000000 * (dur / 1000) * (mem / 1024);
          const rate = pf.serverlessGBsec || 0.000020;
          const reqRate = pf.serverlessReqM || 0.20;
          const gbCost = gbSec * rate;
          const reqCost = invM * reqRate;
          computeCost = gbCost + reqCost;
          lines.push({ label: 'Serverless Compute', formula: Math.round(gbSec) + ' GB-s × $' + rate + '/GB-s', value: gbCost });
          lines.push({ label: 'Serverless Requests', formula: invM + 'M × $' + reqRate + '/M', value: reqCost });
        }
        const trainHr = this.getVal(config, 'sageMaker', 'trainingHours', 10);
        const trainRate = pf.trainingHourly || 1.50;
        const trainCost = trainHr * trainRate;
        if (trainCost > 0) lines.push({ label: 'Training Jobs', formula: trainHr + ' hrs × $' + trainRate + '/hr', value: trainCost });
        total = computeCost + trainCost;
        break;
      }

      case 'appSync': {
        const reqM = this.getVal(config, 'appSync', 'requestsM', 10);
        const costReq = reqM * (pf.reqM || 4.0);
        lines.push({ label: 'GraphQL Requests', formula: reqM + 'M × $' + (pf.reqM || 4.0).toFixed(2) + '/M', value: costReq });
        const dt = this.getVal(config, 'appSync', 'dtGB', 100);
        const costDt = dt * (pf.dtGB || 0.09);
        lines.push({ label: 'Data Transfer', formula: dt + ' GB × $' + (pf.dtGB || 0.09).toFixed(2) + '/GB', value: costDt });
        total = costReq + costDt;
        break;
      }

      case 'iotCore': {
        const msg = this.getVal(config, 'iotCore', 'messagesM', 50);
        const costMsg = msg * (pf.msgM || 1.0);
        lines.push({ label: 'Messages', formula: msg + 'M × $' + (pf.msgM || 1.0).toFixed(2) + '/M', value: costMsg });
        const rules = this.getVal(config, 'iotCore', 'rulesM', 50);
        const costRules = rules * (pf.ruleM || 0.15);
        lines.push({ label: 'Rules Executed', formula: rules + 'M × $' + (pf.ruleM || 0.15).toFixed(2) + '/M', value: costRules });
        total = costMsg + costRules;
        break;
      }

      case 'rekognition': {
        const img = this.getVal(config, 'rekognition', 'imagesM', 1);
        const cost = img * (pf.imageM || 1000);
        lines.push({ label: 'Image Processing', formula: img + 'M × $' + (pf.imageM || 1000).toFixed(2) + '/M', value: cost });
        total = cost;
        break;
      }

      case 'textract': {
        const pages = this.getVal(config, 'textract', 'pagesM', 0.1);
        const cost = pages * (pf.pageM || 1500);
        lines.push({ label: 'Page Extraction', formula: pages + 'M × $' + (pf.pageM || 1500).toFixed(2) + '/M', value: cost });
        total = cost;
        break;
      }

      case 'mediaConvert': {
        const min = this.getVal(config, 'mediaConvert', 'minutesHD', 1000);
        const cost = min * (pf.minHD || 0.017);
        lines.push({ label: 'HD Conversion', formula: min + ' min × $' + (pf.minHD || 0.017).toFixed(3) + '/min', value: cost });
        total = cost;
        break;
      }

      case 'cloudTrail': {
        const ev = this.getVal(config, 'cloudTrail', 'eventsM', 10);
        const cost = ev * (pf.eventM || 1.0);
        lines.push({ label: 'Data Events', formula: ev + 'M × $' + (pf.eventM || 1.0).toFixed(2) + '/M', value: cost });
        total = cost;
        break;
      }

      case 'backup': {
        const wGB = this.getVal(config, 'backup', 'warmGB', 100);
        const costW = wGB * (pf.warmGB || 0.05);
        lines.push({ label: 'Warm Storage', formula: wGB + ' GB × $' + (pf.warmGB || 0.05).toFixed(2) + '/GB', value: costW });
        const cGB = this.getVal(config, 'backup', 'coldGB', 0);
        const costC = cGB * (pf.coldGB || 0.01);
        lines.push({ label: 'Cold Storage', formula: cGB + ' GB × $' + (pf.coldGB || 0.01).toFixed(2) + '/GB', value: costC });
        total = costW + costC;
        break;
      }

      case 'appRunner': {
        const inst = this.getVal(config, 'appRunner', 'instances', 2);
        const vcpu = this.getVal(config, 'appRunner', 'vcpu', 1);
        const mem = this.getVal(config, 'appRunner', 'memGB', 2);
        const cpuRate = pf.cpuHour || 0.064;
        const memRate = pf.memHour || 0.007;
        const cost = inst * 730 * ((vcpu * cpuRate) + (mem * memRate));
        lines.push({ label: 'AppRunner Instances', formula: inst + ' Inst × 730 hrs', value: cost });
        total = cost;
        break;
      }

      case 'elasticBeanstalk': {
        lines.push({ label: 'Elastic Beanstalk (Free)', formula: 'Compute billed separately under EC2', value: 0 });
        total = 0;
        break;
      }

      case 'fsx': {
        const type = this.getVal(config, 'fsx', 'type', 'windows');
        const deploy = this.getVal(config, 'fsx', 'deployment', 'singleAz');
        const sGB = this.getVal(config, 'fsx', 'storageGB', 500);
        const rateKey = type + (deploy === 'multiAz' ? 'Multi' : 'Single');
        const sRate = pf[rateKey] || 0.13;
        const storageCost = sGB * sRate;
        lines.push({ label: 'FSx Storage (' + type + ')', formula: sGB + ' GB × $' + sRate + '/GB', value: storageCost });
        const tp = this.getVal(config, 'fsx', 'throughputMBps', 8);
        const tpCost = tp * (pf.throughputRate || 1.18);
        lines.push({ label: 'Throughput Capacity', formula: tp + ' MB/s × $' + (pf.throughputRate || 1.18) + '/MBps', value: tpCost });
        total = storageCost + tpCost;
        break;
      }

      case 'certificateManager': {
        lines.push({ label: 'ACM Public Certs are free', formula: '0.00', value: 0 });
        total = 0;
        break;
      }

      case 'systemsManager': {
        const inst = this.getVal(config, 'systemsManager', 'advancedInst', 0);
        const costInst = inst * 730 * (pf.instHour || 0.00695);
        if (costInst > 0) {
          lines.push({ label: 'Advanced Instances', formula: inst + ' Inst × 730 hrs', value: costInst });
        }
        const calls = this.getVal(config, 'systemsManager', 'paramCallsM', 10);
        const costCalls = calls * (pf.callM || 0.05);
        lines.push({ label: 'Parameter Calls', formula: calls + 'M × $' + (pf.callM || 0.05).toFixed(2) + '/M', value: costCalls });
        total = costInst + costCalls;
        break;
      }

      case 'ecr': {
        const gb = this.getVal(config, 'ecr', 'storageGB', 50);
        const cost = gb * (pf.storageGB || 0.10);
        lines.push({ label: 'ECR Storage', formula: gb + ' GB × $' + (pf.storageGB || 0.10).toFixed(2) + '/GB', value: cost });
        total = cost;
        break;
      }

      case 'privateLink': {
        const eps = this.getVal(config, 'privateLink', 'endpoints', 1);
        const hrCost = eps * 730 * (pf.endpointHourly || 0.01);
        lines.push({ label: 'Endpoint Hourly', formula: eps + ' endpoints × 730 hrs × $' + (pf.endpointHourly || 0.01).toFixed(2) + '/hr', value: hrCost });
        const dataGB = this.getVal(config, 'privateLink', 'dataGB', 100);
        const dataCost = dataGB * (pf.dataGB || 0.01);
        lines.push({ label: 'Data Processed', formula: dataGB + ' GB × $' + (pf.dataGB || 0.01).toFixed(2) + '/GB', value: dataCost });
        total = hrCost + dataCost;
        break;
      }

      case 'client': {
        // The client node represents end users — it is NOT a billable AWS resource.
        // No lines pushed → Cost Evaluation panel is hidden entirely for this node.
        total = 0;
        break;
      }

      case 'iam':
      case 'securityGroup':
      case 'autoScalingGroup': {
        total = 0;
        break;
      }
    }

    return total;
  }

  getCostBreakdown(node: ArchitectureNode, region: string = 'us-east-1', allNodes?: ArchitectureNode[]): CostBreakdown {
    const model = this.costModel[node.type];
    const config: any = node.config;
    const lines: CostBreakdownLine[] = [];
    let freeTierNote: string | undefined;

    if (model?.costEvaluation?.freeTier?.description) {
      freeTierNote = model.costEvaluation.freeTier.description;
    }

    const basePf = fallbackPrices.services[node.type] || {};
    const regionalPf = this.getPricingFactorsForRegion(node.type, region);

    const nodesList = allNodes || this.activeNodes;

    const baseTotal = this.evaluateServiceCost(node, basePf, config, [], nodesList);
    const regionalTotal = this.evaluateServiceCost(node, regionalPf, config, lines, nodesList);

    const regOpt = this.regions.find(r => r.code === region) || this.regions[0];
    const diff = regionalTotal - baseTotal;

    if (Math.abs(diff) > 0.001) {
      lines.push({
        label: 'Regional Adjustment',
        formula: `Adjusted from base $${baseTotal.toFixed(2)} to ${regOpt.code}`,
        value: diff,
        note: `Base pricing adjusted for ${regOpt.name} rates`
      });
    }

    return { lines, total: Math.max(0, regionalTotal), freeTierNote };
  }

  calculateNodeCostUsd(node: ArchitectureNode, region: string = 'us-east-1', allNodes?: ArchitectureNode[]): number {
    return this.getCostBreakdown(node, region, allNodes).total;
  }
}
